# SEMPRE QUE QUISER EDITAR ALGO NA TEAL DENTRO DO CÓDIGO EM PYTHON, É SO COLOCAR UM ID AO ITEM QUE EU QUERO. ID ÚNICO!!

GridLayout:
    cols:1

    Label:
        text: "Cotação das moedas em tempo real!"
    Label:
        id: moeda1
        text: "1º texto"

    Label:
        id: moeda2
        text: "2º texto"

    Label:
        id: moeda3
        text: "3º texto"

    Label:
        id: moeda4
        text: "3º texto"